<?php

declare(strict_types=1);

namespace App\Models;

use Database\Factories\DomainFactory;
use Illuminate\Database\Eloquent\Concerns\HasUlids;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Carbon;

/**
 * @property int $id
 * @property string $public_id
 * @property string $host
 * @property bool $is_primary
 * @property Carbon|null $verified_at
 * @property string $verification_token
 * @property Carbon|null $last_checked_at
 * @property string|null $last_failure
 */
final class Domain extends Model
{
    /** @use HasFactory<DomainFactory> */
    use HasFactory, HasUlids;

    /**
     * Nothing is fillable from request input: the host is normalised and the
     * token generated by the registering service.
     *
     * @var list<string>
     */
    protected $fillable = [];

    /**
     * @var list<string>
     */
    protected $hidden = ['verification_token'];

    /**
     * @return list<string>
     */
    public function uniqueIds(): array
    {
        return ['public_id'];
    }

    public function getRouteKeyName(): string
    {
        return 'public_id';
    }

    /**
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'is_primary' => 'boolean',
            'verified_at' => 'datetime',
            'last_checked_at' => 'datetime',
        ];
    }

    public function isVerified(): bool
    {
        return $this->verified_at !== null;
    }

    /**
     * A domain serves links only once verified. An unverified host that already
     * points at the instance would otherwise be served before the operator has
     * shown they control it.
     */
    public function servesLinks(): bool
    {
        return $this->isVerified();
    }

    public static function normaliseHost(string $host): string
    {
        $host = mb_strtolower(trim($host));
        $host = preg_replace('#^https?://#', '', $host) ?? $host;
        $host = explode('/', $host)[0];

        return rtrim($host, '.');
    }

    protected static function newFactory(): DomainFactory
    {
        return DomainFactory::new();
    }
}
